### ISSUE TITLE
Custom assistant without OpenAI to use the custom GPT for private and sensitive data

### ISSUE THREAD

**Issue by MatchuPitchu** [BuilderIO/gpt-crawler#10]
The project is great, thank you very much for it.

Is there a way to do the final step, build a custom GPT, without OpenAI to avoid misuse of private or sensitive data?

**Comment by steve8708** [comment]
None that I know of, but its possible there will be open source alternatives in the future that this project could integrate with!

**Comment by theoparis** [comment]
This exists and could possibly be used here: https://github.com/withcatai/node-llama-cpp
It is a wrapper around llama.cpp which supports a lot of different models.
