### ISSUE TITLE
Multiple Selectors

### ISSUE THREAD

**Issue by gummipunkt** [BuilderIO/gpt-crawler#28]
Is it possible to use multiple selectors?

**Comment by InsightfulFuture** [comment]
Use `:is()` then put a comma separated list of selectors inside

**Comment by gummipunkt** [comment]
Thanks, but it doesn't work:

`
selector: "is: (.tab-content, .article, .manu-content, #handle-tab-lightning)",
`
(replaced only here ' with ")

**Comment by InsightfulFuture** [comment]
No space after the is, it’s `:is(…)` not `:is (…)`

**Comment by gummipunkt** [comment]
Thanks, solved this problem, but the next one is right around the corner:

`WARN  PlaywrightCrawler: Reclaiming failed request back to the list or queue. page.waitForSelector: Unexpected token "(" while parsing selector "is:(.tab-content, .article, .manu-content, #handle-tab-lightning)"`

**Comment by InsightfulFuture** [comment]
It’s not `is:(…)`, it’s `:is(…)`

**Comment by gummipunkt** [comment]
> @gummipunkt It’s not `is:(…)`, it’s `:is(…)`

I'm just an idiot. Thanks a lot.

**Comment by mahdii0908** [comment]
Hi,

I am trying to use the :is as stated above - The code runs, but I only get the first selector:

`selector: `:is(.tc_richcontent, .tc_page__body__standfirst)``

only gives me .tc_richcontent in the output. Any suggestions to fix this?
