### ISSUE TITLE
[Feature Request] A Way to Split a Knowledge File into Multiple Files

### ISSUE THREAD

**Issue by VoxAndrews** [BuilderIO/gpt-crawler#44]
One issue I've been running into is some pages, or amounts of pages, that I am scraping are too large for one knowledge file, and ChatGPT complains there is too much text in the file for it to use. So I thought maybe there should be an option which allows me to split a knowledge file into multiple knowledge files so that I can feed it however many smaller files as opposed to one large one.

Maybe an option in the 'config.ts' file like:

- splitKnownledgeFile: 3;

Where the default is 1 (So no splitting), but when you set it to any higher number, it will split a knowledge file into multiple knowledge files with a number suffix.

**Comment by guillermoscript** [comment]
I could add that option, but I think it would be best to split by file size so if you want to have X amount of files with same size, could you share whats the limit gpt is telling you about the file?

**Comment by VoxAndrews** [comment]
Honestly probably that's the smarter way of doing it, haha. The main reason why I suggested it by text amount was because it seemed GPT was saying the file contained too much text rather than it being too large of a file, but that could just be its own way of saying the file itls too large. I'll try to get a screenshot of the specific error and see if I can show you it.

**Comment by VoxAndrews** [comment]
Here's the error I get. Based on the wording, it is just the file size rather than the word count, although I could be wrong. This is with an 18.5 MB file, but based on my testing, it seems at the moment GPT doesn't like files that are 7 MB or larger. To be safe I would set the limit to 6 MB or 6.5 MB as they seemed to work for me, but best for you to test too just to see.

![image](https://github.com/BuilderIO/gpt-crawler/assets/26544407/e372faff-6e47-4620-af9f-a8afc34753de)

**Comment by iperzic** [comment]
I don't think that file size is a metric that directly determines this. Since GPTs interpret tokens, so we should probably focus on that, rather than looking at file size

**Comment by guillermoscript** [comment]
good gotcha, the final token for each file should not exceed X number, let me see what I can do.

**Comment by VoxAndrews** [comment]
Cheers everyone!

**Comment by guillermoscript** [comment]
i created a draft [PR](https://github.com/BuilderIO/gpt-crawler/pull/62) you can check it @VoxAndrews  @iperzic  if you want still is not complete yet as i have to test more, but for know if you guys want to take a look, there it is
