### ISSUE TITLE
Comparison with well-established crawlers

### ISSUE THREAD

**Issue by dandv** [BuilderIO/gpt-crawler#75]
How exactly is this project different from an established crawler that would just dump the HTML text into the `.html` field of a JSON array?

It's got 12k stars, but it lacks basic features like canonicalizing links (see #73) or preserving links (#74).

**Comment by FTAndy** [comment]
Yeah, the idea of the project is great, but it lacks so many features to make it perfect.

**Comment by steve8708** [comment]
could you suggest some examples of well established crawlers you think integration with would be better? 

This project is built on [crawlee](https://github.com/apify/crawlee) which is a pretty robust crawler, but certainly open to better alternatives

**Comment by razaanstha** [comment]
I guess instead of just returning plain text maybe try something like [turndown](https://github.com/mixmark-io/turndown) so it preserves the links and converts html to markdown in well formatted way and highly customizable? You can try the [demo here](https://mixmark-io.github.io/turndown/)
